In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# Feature Selection
df = df[["age","fare","survived"]].copy()
df

      age     fare  survived
0    22.0   7.2500         0
1    38.0  71.2833         1
2    26.0   7.9250         1
3    35.0  53.1000         1
4    35.0   8.0500         0
..    ...      ...       ...
886  27.0  13.0000         0
887  19.0  30.0000         1
888   NaN  23.4500         0
889  26.0  30.0000         1
890  32.0   7.7500         0

[891 rows x 3 columns]

In [ ]:
df = df.dropna()
df

      age     fare  survived
0    22.0   7.2500         0
1    38.0  71.2833         1
2    26.0   7.9250         1
3    35.0  53.1000         1
4    35.0   8.0500         0
..    ...      ...       ...
885  39.0  29.1250         0
886  27.0  13.0000         0
887  19.0  30.0000         1
889  26.0  30.0000         1
890  32.0   7.7500         0

[714 rows x 3 columns]

In [ ]:
# Splitting data into the Independent and Dependent Data
X = df[["age","fare"]]
y = df["survived"]

In [ ]:
X.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [ ]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [ ]:
# Splling data into the Training and Testing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((571, 2), (143, 2), (571,), (143,))

In [ ]:
# Scalling StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 6.68025202e-02, -2.93819129e-01],
       [-2.72964097e-01, -4.16381382e-01],
       [-1.15080322e-03, -3.83154632e-01],
       ...,
       [ 7.46335754e-01,  2.00720098e+00],
       [ 2.02709167e-01, -2.93819129e-01],
       [ 2.02709167e-01, -5.48787702e-01]])

In [ ]:
X_test

array([[ 8.14289078e-01, -4.45739956e-01],
       [-1.83589054e+00, -3.29654274e-01],
       [-6.91041266e-02, -1.83285370e-01],
       [-4.08870744e-01,  6.90890288e-01],
       [ 8.82242401e-01, -5.77976690e-01],
       [-1.49612392e+00,  3.37443833e-02],
       [ 2.02709167e-01, -3.88201835e-01],
       [ 1.62972896e+00, -2.43851813e-01],
       [-1.37057450e-01, -5.48787702e-01],
       [-4.76824067e-01, -5.48198189e-01],
       [-8.84544008e-01,  4.42567873e-01],
       [ 1.68732505e-01, -4.45739956e-01],
       [ 6.68025202e-02,  4.42567873e-01],
       [ 5.42475784e-01, -5.48787702e-01],
       [ 3.38615814e-01,  9.63512453e+00],
       [-4.76824067e-01, -4.76023178e-01],
       [-4.42847405e-01, -5.62245566e-01],
       [-9.52497331e-01,  4.62336760e-01],
       [-2.05010773e-01, -4.45739956e-01],
       [ 1.62972896e+00,  4.91021027e-01],
       [-9.52497331e-01,  2.38660848e-01],
       [ 1.35791566e+00, -1.83285370e-01],
       [-1.42817059e+00, -4.00399917e-01],
       [ 3.38615814e-01,  9.63512453e+00],
       [-5.44777390e-01, -5.19429128e-01],
       [-8.84544008e-01, -5.33308938e-01],
       [-9.52497331e-01, -5.16400806e-01],
       [-2.72964097e-01, -2.92809688e-01],
       [-1.05442732e+00, -4.16381382e-01],
       [ 5.42475784e-01, -5.33308938e-01],
       [-6.12730714e-01, -5.09839441e-01],
       [-1.42817059e+00, -1.42040507e-02],
       [ 4.06569137e-01, -1.75462205e-01],
       [ 3.38615814e-01, -5.64349240e-01],
       [ 4.74522461e-01, -5.48198189e-01],
       [ 4.06569137e-01, -3.56909173e-01],
       [ 2.70662490e-01, -1.83285370e-01],
       [ 1.76563561e+00,  8.50836541e-03],
       [ 2.10540222e+00, -3.18692632e-02],
       [ 1.42586899e+00, -5.51731231e-01],
       [-1.42817059e+00, -2.93819129e-01],
       [-6.80684037e-01, -5.48198189e-01],
       [ 4.06569137e-01,  1.71446317e+00],
       [ 1.62972896e+00, -4.25551142e-01],
       [ 1.49382231e+00,  8.99844516e-01],
       [-6.91041266e-02, -4.96211992e-01],
       [ 2.70662490e-01, -5.20580775e-02],
       [-6.12730714e-01, -1.42040507e-02],
       [ 6.78382431e-01, -7.08194542e-01],
       [ 1.22200902e+00,  9.12825040e-02],
       [ 4.74522461e-01,  3.63831497e-01],
       [-4.08870744e-01, -4.45739956e-01],
       [-2.05010773e-01,  3.63831497e-01],
       [-1.37057450e-01, -2.53441500e-01],
       [-3.40917420e-01, -5.65863401e-01],
       [ 1.83358893e+00, -4.96211992e-01],
       [-1.37057450e-01,  2.42698611e-01],
       [-1.83589054e+00, -7.45181334e-02],
       [-2.72964097e-01, -5.49627557e-01],
       [ 2.17335555e+00, -4.96211992e-01],
       [ 1.90154225e+00, -1.72181522e-01],
       [-3.40917420e-01, -5.51898798e-01],
       [ 1.01814905e+00, -1.78238167e-01],
       [-8.84544008e-01, -5.33308938e-01],
       [-7.48637361e-01, -4.96211992e-01],
       [ 1.15405569e+00, -1.91613256e-01],
       [-1.63203056e+00, -4.56339084e-01],
       [-5.44777390e-01,  4.02190244e-01],
       [ 6.68025202e-02, -5.48198189e-01],
       [ 2.02709167e-01, -6.07250470e-01],
       [-8.84544008e-01, -5.33308938e-01],
       [ 2.17335555e+00,  9.06910601e-01],
       [-9.52497331e-01, -2.99371052e-01],
       [-6.80684037e-01, -6.27186924e-01],
       [ 1.01814905e+00, -5.67377562e-01],
       [-6.80684037e-01, -5.48198189e-01],
       [-7.48637361e-01, -4.96211992e-01],
       [-8.16590684e-01, -5.51731231e-01],
       [ 3.28258585e-02, -5.51731231e-01],
       [-1.29226395e+00,  1.71446317e+00],
       [-1.29226395e+00, -7.67893750e-02],
       [ 6.68025202e-02,  3.41623801e-01],
       [ 6.78382431e-01, -5.16905526e-01],
       [-7.48637361e-01, -5.02858149e-01],
       [-3.40917420e-01, -5.48787702e-01],
       [-6.80684037e-01, -5.33308938e-01],
       [-1.42817059e+00, -7.67893750e-02],
       [ 7.12359093e-01, -5.51731231e-01],
       [-7.48637361e-01, -5.53750113e-01],
       [-6.12730714e-01,  7.75683308e-01],
       [ 1.01814905e+00, -1.72181522e-01],
       [ 5.42475784e-01,  3.88526543e+00],
       [ 1.35791566e+00, -4.96211992e-01],
       [-6.91041266e-02, -5.65948194e-01],
       [ 2.70662490e-01, -2.43851813e-01],
       [-2.72964097e-01, -5.48198189e-01],
       [-4.08870744e-01,  9.70672933e-01],
       [-6.91041266e-02, -1.02530113e-01],
       [-1.15080322e-03, -4.45739956e-01],
       [ 6.10429107e-01, -1.20195326e-01],
       [-1.37057450e-01, -4.45739956e-01],
       [-7.48637361e-01, -1.83285370e-01],
       [-1.15080322e-03, -5.62330359e-01],
       [-1.83589054e+00, -2.82715281e-01],
       [-1.76793721e+00,  7.91692154e-02],
       [ 2.70662490e-01, -2.84229442e-01],
       [-6.80684037e-01, -5.49627557e-01],
       [ 4.06569137e-01,  8.83693465e-01],
       [ 9.50195724e-01, -5.48198189e-01],
       [ 6.78382431e-01,  7.91692154e-02],
       [-1.37057450e-01,  4.32388672e-01],
       [-6.12730714e-01, -5.48198189e-01],
       [-1.42817059e+00, -7.45181334e-02],
       [ 1.49382231e+00, -9.24357060e-02],
       [-8.84544008e-01, -5.64349240e-01],
       [-1.15080322e-03, -4.56339084e-01],
       [ 1.34755844e-01, -3.88201835e-01],
       [-1.08840398e+00, -4.81237948e-01],
       [-6.91041266e-02, -5.45674587e-01],
       [ 8.82242401e-01, -5.45674587e-01],
       [-8.84544008e-01,  1.49036733e+00],
       [-1.29226395e+00,  2.38660848e-01],
       [-3.40917420e-01, -3.48833647e-01],
       [-6.80684037e-01, -5.49627557e-01],
       [-3.40917420e-01,  2.35142026e+00],
       [-2.72964097e-01, -5.48955269e-01],
       [-6.12730714e-01, -5.33308938e-01],
       [-8.84544008e-01, -4.65928770e-01],
       [-6.91041266e-02, -5.49207629e-01],
       [ 9.50195724e-01, -1.48544459e-01],
       [-3.40917420e-01, -5.51226511e-01],
       [-1.37057450e-01, -5.48198189e-01],
       [-2.72964097e-01, -3.28897193e-01],
       [ 2.70662490e-01, -4.96211992e-01],
       [-1.90384386e+00, -2.82715281e-01],
       [-5.44777390e-01, -5.61825638e-01],
       [ 2.02709167e-01, -5.16400806e-01],
       [ 4.74522461e-01, -1.08586757e-01],
       [-1.36021727e+00, -1.44926623e-01],
       [-1.97179718e+00,  9.30490252e-02],
       [ 3.38615814e-01, -5.65863401e-01],
       [-6.12730714e-01, -4.96211992e-01],
       [-7.48637361e-01, -1.77565879e-01]])

In [ ]:
# Building ANN Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
#!pip install tensorflow
# lg = LinearRegression()
# lg.fit(training_data)
# lg.predict(testing_data)
# accuracy

In [ ]:
model = Sequential()

In [ ]:
# Input + Hidden Layer
model.add(Dense(units=8,activation="relu", input_dim=2))
# Hidden Layers
model.add(Dense(units=4,activation="relu"))
# Output Layer
model.add(Dense(units=1,activation="sigmoid")) # 10 = 1, 0 = 0.5, -10 = 0 | 0=Not Survived , 1 = Survived

In [ ]:
# Compile
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
# Training the model
model.fit(X_train,y_train,epochs=50,batch_size=10)

Epoch 1/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.5902 - loss: 0.7003
Epoch 2/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.5902 - loss: 0.6808
Epoch 3/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5902 - loss: 0.6714
Epoch 4/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5902 - loss: 0.6642
Epoch 5/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5902 - loss: 0.6567
Epoch 6/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5902 - loss: 0.6510
Epoch 7/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5902 - loss: 0.6458
Epoch 8/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5902 - loss: 0.6400
Epoch 9/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5902 - loss: 0.6347
Epoch 10/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5902 - loss: 0.6276
Epoch 11/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6077 - loss: 0.6256
Epoch 12/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6900 - loss: 0.6195
Epoch 13/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6900 - loss: 0.6178
Epoch 14/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6192
Epoch 15/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6970 - loss: 0.6147
Epoch 16/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6953 - loss: 0.6137
Epoch 17/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7005 - loss: 0.6118
Epoch 18/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6988 - loss: 0.6082
Epoch 19/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6988 - loss: 0.6106
Epoch 20/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7023 - loss: 0.6078
Epoch 21/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7040 - loss: 0.6082
Epoch 22/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7005 - loss: 0.6067
Epoch 23/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7023 - loss: 0.6066
Epoch 24/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7005 - loss: 0.6057
Epoch 25/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7023 - loss: 0.6042
Epoch 26/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7075 - loss: 0.6039
Epoch 27/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6970 - loss: 0.6012
Epoch 28/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7005 - loss: 0.5996
Epoch 29/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7040 - loss: 0.6005
Epoch 30/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7058 - loss: 0.5979
Epoch 31/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7058 - loss: 0.5984
Epoch 32/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7093 - loss: 0.5972
Epoch 33/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7075 - loss: 0.5964
Epoch 34/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7075 - loss: 0.5965
Epoch 35/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7040 - loss: 0.5981
Epoch 36/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7075 - loss: 0.5947
Epoch 37/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7110 - loss: 0.5955
Epoch 38/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7023 - loss: 0.5920
Epoch 39/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7040 - loss: 0.5955
Epoch 40/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7040 - loss: 0.5925
Epoch 41/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7058 - loss: 0.5939
Epoch 42/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7110 - loss: 0.5917
Epoch 43/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7005 - loss: 0.5892
Epoch 44/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7093 - loss: 0.5916
Epoch 45/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7023 - loss: 0.5915
Epoch 46/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7110 - loss: 0.5908
Epoch 47/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7005 - loss: 0.5894
Epoch 48/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7058 - loss: 0.5881
Epoch 49/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7040 - loss: 0.5900
Epoch 50/50
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7058 - loss: 0.5913

In [ ]:
# Evaluate Model
loss, accuracy = model.evaluate(X_test,y_test)
print("Accuracy:- ", accuracy)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6364 - loss: 0.6633
Accuracy:-  0.6363636255264282

In [ ]:
# Preiction
y_pred = model.predict(X_test)
print(y_pred > 0.5)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
[[False]
 [ True]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [ True]]

In [ ]:
# ReLu
# if input is positive :- Keep it 1
# if input is negative :- make it 0 -1 :- 0